### ISSUE TITLE
Enhancements and fixes for embedded use

### ISSUE THREAD

**Issue by JensOgorek** [zauberzeug/owl#3]
- [ ] Configurable size for Tokenizer Advance (default 4096, hotfix 256) #99 
- [x] faster '\0' handling without size allocation #99 
- [x] handle escape character size correctly #24 
- [x] remove minimum size of 4096 #23 (gen_parser.sh)
- [x] Reservation_amount #7 (gen_parser.sh)
- [ ] add better exception handling with better error codes (e.g. malloc from #99)
- [ ] improve code for embedded systems
- [ ] change gen_parser.sh and re-enable it for the GitHub action

**Comment by ianh** [comment]
Let me know if it would be useful for any of this to be upstreamed!

**Comment by JensOgorek** [comment]
> Let me know if it would be useful for any of this to be upstreamed!

Thanks for the reply. That is a great idea! We need to test if some of the changes were just fighting symptoms of the tokenizer advance memory allocation, but I think #6 and #7 could possibly be candidates for getting upstreamed.

**Comment by ianh** [comment]
Versions of #6 and #7 are upstreamed as https://github.com/ianh/owl/commit/4213bbe653532398550fa74f4c88d9262a10253c and https://github.com/ianh/owl/commit/aeb02a7559824ec4edab2663c9d62b0706ab28d1.  Thanks for finding that string escaping bug -- I'm not sure how nobody caught it until now!  The reservation amount part of #5 appears to be a real off-by-one error, too, and I threw in the change to the while loop as well (https://github.com/ianh/owl/commit/c2be1d5feed64a638040dc8d59adfc158f49c0d6 and https://github.com/ianh/owl/commit/a3470af1e335926ba5836ad97ac715795329aab1).

**Comment by JensOgorek** [comment]
Thanks! We will validate the other changes from #5 after the holidays. The same goes for the changes for the tokenizer's memory allocation size and the check if the allocation worked.
We would clean up this fork and target the changes directly to the main repository, if that is wanted.

**Comment by ianh** [comment]
Sounds good.  It's up to you if you want to keep the fork around; my main interest is getting the fixes available to anyone else who might be using owl.

**Comment by JensOgorek** [comment]
Perfect, we’ll most likely close it then. Getting the fixes out is also our main goal. Previously, we had the changes directly in the parsed header file, but we decided to maintain and share them in a better way.

**Comment by JensOgorek** [comment]
Everything we had right now is added to owl's main branch
